name: fundus-lesion-phenotyping
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - antlr-python-runtime=4.9.3
  - arrow-cpp=19.0.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - debugpy=1.6.7
  - ffmpeg=4.3
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - hf-xet=1.1.8
  - huggingface_hub=0.36.0
  - idna=3.7
  - importlib_metadata=8.2.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.0.15
  - libcurand=10.3.7.37
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multiprocess=0.70.15
  - ncurses=6.4
  - nettle=3.7.3
  - numba=0.61.2
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.18
  - orc=2.1.1
  - pillow=10.4.0
  - pip=24.2
  - propcache=0.3.1
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pynndescent=0.5.13
  - pysocks=1.7.1
  - python=3.11.9
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyzmq=25.1.2
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - s2n=1.3.27
  - scikit-learn=1.7.2
  - setuptools=72.1.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tornado=6.4.1
  - typing_extensions=4.15.0
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - wheel=0.43.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.3.1
      - accelerate==1.4.0
      - addict==2.4.0
      - aider-chat==0.50.1
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.3
      - aiosignal==1.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - alembic==1.16.4
      - anndata==0.12.6
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - annoy==1.17.3
      - anthropic==0.34.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - argparse==1.4.0
      - array-api-compat==1.12.0
      - asttokens==2.4.1
      - attrs==25.4.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - boto3==1.40.9
      - botocore==1.40.9
      - bunch==1.0.1
      - certifi==2024.7.4
      - cffi==1.17.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmappy==4.0.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==3.6.0
      - decorator==5.1.1
      - diff-match-patch==20230430
      - diffusers==0.32.2
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - dominate==2.9.1
      - donfig==0.8.1.post1
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fairscale==0.4.13
      - fastapi==0.128.0
      - filelock==3.15.4
      - flake8==7.1.1
      - flash-attn==2.8.3
      - flatbuffers==25.9.23
      - fonttools==4.53.1
      - formulaic==1.2.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-crc32c==1.7.1
      - greenlet==3.2.4
      - grep-ast==0.3.3
      - grpcio==1.74.0
      - h11==0.14.0
      - h5py==3.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - ietk-ret==0.1.1
      - igraph==1.0.0
      - imageio==2.36.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - interface-meta==1.3.0
      - ipykernel==6.29.5
      - ipython==8.26.0
      - jedi==0.19.1
      - jiter==0.5.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonargparse==4.41.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - kiwisolver==1.4.5
      - kneed==0.8.5
      - kornia==0.7.2
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - legacy-api-wrap==1.5
      - leidenalg==0.11.0
      - lifelines==0.30.0
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - litellm==1.43.9
      - lpips==0.1.4
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmcv==1.7.1
      - mmcv-full==1.7.2
      - mmengine==0.10.7
      - monai==1.5.1
      - multidict==6.0.5
      - narwhals==2.3.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nibabel==5.3.2
      - npeet==1.0.1
      - numcodecs==0.16.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - onnxruntime==1.23.2
      - openai==1.40.6
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - optuna==4.4.0
      - packaging==25.0
      - pacmap==0.8.0
      - pandas==2.2.2
      - parso==0.8.4
      - pathspec==0.12.1
      - patsy==0.5.6
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.2.2
      - prettytable==3.16.0
      - prompt-toolkit==3.0.47
      - protobuf==6.31.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pvbm==3.0.0.0
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyecharts==2.0.8
      - pyflakes==3.2.0
      - pygments==2.18.0
      - pykwalify==1.8.0
      - pymupdf==1.24.9
      - pymupdf4llm==0.0.10
      - pymupdfb==1.24.9
      - pynvml==12.0.0
      - pypager==3.0.1
      - pypandoc==1.13
      - pyparsing==3.1.2
      - pypdf==4.3.1
      - pyperclip==1.9.0
      - pyradiomics==3.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.21
      - pytorch-lightning==2.5.5
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.7.24
      - rich==13.7.1
      - rpds-py==0.20.0
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.13.1
      - safetensors==0.5.2
      - scanpy==1.11.5
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.34.1
      - session-info2==0.2.3
      - simpleitk==2.5.2
      - simplejson==3.20.1
      - simsimd==6.5.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sounddevice==0.5.0
      - soundfile==0.12.1
      - soupsieve==2.5
      - sqlalchemy==2.0.43
      - stack-data==0.6.2
      - starlette==0.50.0
      - statsmodels==0.14.6
      - stringzilla==4.1.0
      - swankit==0.2.4
      - swanlab==0.6.8
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - texttable==1.7.0
      - tifffile==2024.9.20
      - tiktoken==0.7.0
      - timm==1.0.20
      - tomli==2.3.0
      - torch-geometric==2.6.1
      - torchinfo==1.8.0
      - torchmetrics==1.8.2
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.55.2
      - tree-sitter==0.21.3
      - tree-sitter-languages==1.10.2
      - triton==3.5.1
      - typeshed-client==2.8.2
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2024.1
      - umap-learn==0.5.9.post2
      - uvicorn==0.40.0
      - visdom==0.2.4
      - wandb==0.21.1
      - wcwidth==0.2.13
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xlsxwriter==3.2.9
      - yapf==0.40.1
      - yarl==1.9.4
      - zarr==3.1.5
      - zipp==3.20.0
prefix: /home/weichy26/miniconda3/envs/fundus-lesion-phenotyping
